server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    discovery:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    availability-zones:
      default: default-zone
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true